---

- name: Include build information file
  include_vars:
    file: "{{ build_info_file }}"
    name: "buildinfo"

- name: Extract build information to vars
  include_tasks: tasks/extract-buildinfo.yml

- name: Replace botte information in formula file
  lineinfile:
    path: "{{ formula_path }}/{{ formula_name }}.rb"
    state: present
    regexp: "sha256 {{ bottle_os }}: (.+)"
    line: "    sha256 {{ bottle_os }}: \"{{ bottle_sha256 }}\""
