name: 'build'

on:
  schedule:
    - cron: "30 22 * * *"
  push:
    branches:
      - master

jobs:
  install-php-arm64:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        brew update || true
        brew upgrade $(brew outdated --formula -q) || true
        brew install vsh-php56
        brew install vsh-php70
        brew install vsh-php71
        brew install vsh-php72
        brew install vsh-php73
        brew install vsh-php74
        brew install vsh-php80
        brew install vsh-php81
        brew install vsh-php82
        brew install vsh-php83
  install-php-x86:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        brew update || true
        brew upgrade $(brew outdated --formula -q) || true
        brew install vsh-php56
        brew install vsh-php70
        brew install vsh-php71
        brew install vsh-php72
        brew install vsh-php73
        brew install vsh-php74
        brew install vsh-php80
        brew install vsh-php81
        brew install vsh-php82
        brew install vsh-php83