name: 'install-test'

on:
  schedule:
    - cron: "30 22 * * *"
  push:
    branches:
      - master

jobs:
  install-php-x86:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v1
    - name: Install php services
      run: |
        brew update || true
        brew upgrade $(brew outdated --formula -q) || true
        brew tap valet-sh/core
        brew install vsh-php56
        brew install vsh-php70
        brew install vsh-php71
        brew install vsh-php72
        brew install vsh-php73
        brew install vsh-php74
        brew install vsh-php80
        brew install vsh-php81
        brew install vsh-php82
        brew install vsh-php83
  install-elasticsearch-x86:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v1
    - name: Install elasticsearch services
      run: |
        brew update || true
        brew upgrade $(brew outdated --formula -q) || true
        brew tap valet-sh/core
        brew install vsh-elasticsearch1
        brew install vsh-elasticsearch2
        brew install vsh-elasticsearch5
        brew install vsh-elasticsearch6
        brew install vsh-elasticsearch7
        brew install vsh-elasticsearch8
  install-opensearch-x86:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v1
    - name: Install opensearch services
      run: |
        brew update || true
        brew upgrade $(brew outdated --formula -q) || true
        brew tap valet-sh/core
        brew install vsh-opensearch1
        brew install vsh-opensearch2
  install-mysql-x86:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v1
    - name: Install mysql services
      run: |
        brew update || true
        brew upgrade $(brew outdated --formula -q) || true
        brew tap valet-sh/core
        brew install vsh-mysql57
        brew install vsh-mysql80
  install-mariadb-x86:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v1
    - name: Install mariadb services
      run: |
        brew update || true
        brew upgrade $(brew outdated --formula -q) || true
        brew tap valet-sh/core
        brew install vsh-mariadb104
        brew install vsh-mariadb106
